on:
  push:
  pull_request:

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: python3.10-test python3.11-test python3.12-test
    strategy:
      matrix:
        tox_env: [py37, py38, py39, py310, py311, py312]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
